#!/usr/bin/python3
import argparse
import pickle
import os.path
from datetime import datetime


parser = argparse.ArgumentParser()

class bcolors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    DEFAULT = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'

days_in_month = [31,29,31,30,31,30,31,31,30,31,30,31]
month_list = ["Jan", "Feb", "Mar", "Apr", "May", "June",\
                            "July", "Aug", "Sept", "Oct", "Nov", "Dec"]
week_list = ["Sun", "Mon", "Tue", "Wed", "Thrus", "Fri", "Sat"]

class Deadline:
    def __init__(self, name=None, date=None, details=None):
        self.name = name
        self.date = date
        self.details = details
    def __repr__(self):
        if self.date.month>datetime.now().month:
            return f"\033[93m{self.name[:15]:>20}  {str(self.date):<15} \033[00m"
        elif self.date.month==datetime.now().month and self.date.date>=datetime.now().day:
            return f"\033[93m{self.name[:15]:>20}  {str(self.date):<15} \033[00m"
        else:
            return f"{self.name[:15]:>20}  {str(self.date):<15} "
    def get_date(self):
        return self.date
    def cmp(self):
        return self.date.cmp()

class Date:
    def __init__(self, date=None, month=None):
        self.date=date
        self.month = month if type(month)==int else month #TODO: styp(month)==int
    def __repr__(self):
        return f"{self.date:<2} {month_list[self.month-1]:<5}"
    def cmp(self):
        return (self.month, self.date)


class Data:
    def __init__(self):
        self.deadlines = []
    def add_deadline(self, name="", date=None, month=None):
        date = int(date)
        month = int(month)
        if date > days_in_month[month-1]:
            print(bcolor.FAIL, "Days in given month: ", days_in_month[month-1])
            print("Deadline not added", bcolor.DEFAULT)
            exit()
        if month > 12:
            print(bcolor.FAIL, "month can't be greater than 12")
            print("Deadline not added", bcolor.DEFAULT)
            exit()
        date = Date(date, month)
        d = Deadline(name, date)
        self.deadlines.append(d)
        self.deadlines.sort(key=lambda x: x.cmp())
        print(f"Added deadline:\t {str(d)}")
    def remove_deadline(self, name=None):
        for i,d in enumerate(self.deadlines):
            if d.name==name:
                delete = self.deadlines.pop(i)
                print(f"Remove deadline:\t {str(delete)}")
                return
        if i+1==len(self.deadlines):
            print(f"\033[91m{name}: No such deadline found\033[00m")

    def print_all(self):
        print("All deadlines:")
        for d in self.deadlines:
            # if d.date.month>=datetime.now().month:
            #     if d.date.date>=datetime.now().day:
            #         print('\033[93m', end='')
            print(d)
        # print('\033[00m')

    def print_upcoming(self):
        print("Upcoming deadlines:")
        for d in self.deadlines:
            if d.date.month>datetime.now().month:
                print(d)
            elif d.date.month==datetime.now().month and d.date.date>=datetime.now().day:
                print(d)

    def save_data(self, data_file):
        with open(data_file, "wb") as f:
            pickle.dump(self, f)



data_file = "/home/amit/Desktop/8th_sem_courses/Deadlines/deadline.pkl"
data = None
if os.path.isfile(data_file):
    with open(data_file, "rb") as f:
        data = pickle.load(f)
else:
    data = Data()

parser.add_argument("-a", "--add", nargs="+", help="Add a new deadline: Name, date, month")
parser.add_argument("-r", "--remove", help="Remove a deadline: -r Name", type=str)
parser.add_argument("--upcoming", action="store_true", help="Shows upcoming deadlines")
parser.add_argument("--all", action="store_true", help="Shows all deadlines including past")

args = parser.parse_args()
if args.add is not None:
    (name, date, month) = args.add
    data.add_deadline(name, date, month)
    data.save_data(data_file)
    data.print_upcoming()

if args.remove is not None:
    name = args.remove
    data.remove_deadline(name)
    data.save_data(data_file)
    data.print_upcoming()

if args.all:
    data.print_all()

if args.upcoming:
    data.print_upcoming()

if not (args.add or args.remove or args.all or args.upcoming):
    data.print_upcoming()


